title: "Alec Kulakowski"
description: false
show_downloads: false
google_analytics: [UA-126265112-1]

collections:
  authors:
    output: true

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "my_author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
